update script adding error codes

diff --git a/UMS/src/cli/setting_sshkey.in b/UMS/src/cli/setting_sshkey.in
--- a/UMS/src/cli/setting_sshkey.in
+++ b/UMS/src/cli/setting_sshkey.in
@@ -10,6 +10,11 @@
 
 set -e
 
+VISHNU_OK=0
+CLI_INVALID_PARAM=10
+CLI_UNKNOWN_OPTION=41
+CLI_ERROR_RUNTIME=16
+
 # Show help
 usage() {
 echo "Usage: vishnu_ssh_setting [OPTION] [login]@MACHINE KEY"
@@ -32,10 +37,6 @@ echo "	 print the help"
 
 # Add a key 
 addkey() {
-  if [ -z $1 ] ; then
-    echo "ERROR : You must specify at leat the remote machine's hostname/IP address" 
-    usage ; exit 1
-  fi
   rmachine=$1
   key_file=$2
   cat ${key_file} | ssh ${rmachine} 'mkdir -p .ssh && cat >> ~/.ssh/authorized_keys'
@@ -43,10 +44,6 @@ addkey() {
 
 # Remove a key 
 removekey() {
-  if [ -z $1 ] ; then
-    echo "ERROR : You must specify at leat the remote machine's hostname/IP address" 
-    usage ; exit 1
-  fi
   rmachine=$1
   key_file=$2
   cat ${key_file} | ssh ${rmachine} 'set -e; \
@@ -63,26 +60,24 @@ removekey() {
 
 # Validate the number of paramters
 validate_params(){
- [ $# -gt $1 ]  && echo "ERROR : Wrong parameters" && usage && exit 1
+ [ $# -ne $1 ]  && echo "ERROR : Wrong number of parameters" && usage && exit ${CLI_INVALID_PARAM}
  echo -n
 }
 
-# Start processing
-if [ -z $1  ] ; then
-  usage && exit 1
-fi
+# Start processing by checking the number of parameters
+validate_params 4 $@
 
 case $1 in 
   -h) usage 
       ;;
-  -a) validate_params 4 $@ ;
-      addkey $2 $3 ;
+  -a) addkey $2 $3 ;
       ;;
-  -r) validate_params 4 $@ ;
-      removekey $2 $3 ;
+  -r) removekey $2 $3 ;
       ;;
-   *) usage && exit 1
+   *) usage && exit ${CLI_UNKNOWN_OPTION}
       ;;
 esac
 
-exit 0
+[ $? -ne 0 ] && exit ${CLI_ERROR_RUNTIME}
+
+exit ${VISHNU_OK}
